list_reverse
kat3chrome/FOctothorpe pull request #1
Opened 2021-02-12 21:06 UTC by kat3chrome

2021-02-13 08:58 UTC, yurii-litvinov requested changes

2021-02-13 08:58 UTC, yurii-litvinov commented on tasks/hw1/list_reverse/list_reverse/list_reverse/Program.fs
> +    |[x] -> [x]
Это не обязательно, tail в следующем шаблоне вполне может быть пустым, так что список из одного элемента им поматчится.

2021-02-13 08:58 UTC, yurii-litvinov commented on tasks/hw1/list_reverse/list_reverse/list_reverse/Program.fs
> +    |head::tail -> reverse tail @ [head]
Не-а. Во-первых, это требует квадратичного времени, во-вторых, настоящего рекурсивного вызова (попробуйте сделать `reverse [1..100000]`). Используйте аккумулятор.

2021-02-13 08:58 UTC, yurii-litvinov commented on tasks/hw1/list_reverse/list_reverse/list_reverse/Program.fs
> +    |[] -> []
По стайлгайду принято пробел после `|`

2021-02-13 22:37 UTC, kat3chrome commented on tasks/hw1/list_reverse/list_reverse/list_reverse/Program.fs
> +    |[x] -> [x]
![image](https://user-images.githubusercontent.com/47758828/107863381-1059b980-6e65-11eb-8b51-ad8d651544a9.png)

Студия советует - стоит ли мне спорить с машиной?)

2021-02-15 10:44 UTC, yurii-litvinov commented on tasks/hw1/list_reverse/list_reverse/list_reverse/Program.fs
> +    |[x] -> [x]
У Вас же есть паттерн `[]`. Значит, там ещё что-то не так

2021-02-15 10:45 UTC, yurii-litvinov approved these changes
Ну окей, зачтена. Так-то тоже будет работать, хоть одно условие лишнее

2021-02-15 11:59 UTC, merged