list_find
kat3chrome/FOctothorpe pull request #2
Opened 2021-02-14 00:37 UTC by kat3chrome

2021-02-14 09:53 UTC, yurii-litvinov requested changes
Надо немного поправить

2021-02-14 09:53 UTC, yurii-litvinov commented on tasks/hw1/list_find/list_find/list_find/Program.fs
> +       | [] -> -1
Не, я же не зря про Option рассказывал. Если вернуть -1, вызывающий может забыть проверить на корректность, обратиться к списку по индексу и упасть.

2021-02-14 09:53 UTC, yurii-litvinov commented on tasks/hw1/list_find/list_find/list_find.sln
> +Project("{F2A71F9B-5D33-465A-A702-920D77279786}") = "list_find", "list_find\list_find.fsproj", "{68FEB666-5857-49BC-8E9E-9B19FAB78E6B}"
Кстати, в именовании проектов и решений действует обычный дотнетовский стайлгайд, то есть CamelCase

2021-02-14 11:36 UTC, kat3chrome commented on tasks/hw1/list_find/list_find/list_find.sln
> +Project("{F2A71F9B-5D33-465A-A702-920D77279786}") = "list_find", "list_find\list_find.fsproj", "{68FEB666-5857-49BC-8E9E-9B19FAB78E6B}"
Понял, дальше буду ему следовать

2021-02-15 11:11 UTC, yurii-litvinov approved these changes
Окей, зачтена

2021-02-15 11:11 UTC, yurii-litvinov commented on tasks/hw1/list_find/list_find/list_find/Program.fs
> +       | head :: tail when head = value -> Some(index)
Лучше `| head :: _ `, чтобы неиспользуемый tail не смущал компилятор. Вообще, шаблон `_` означает "всё, что угодно, нам пофиг"

2021-02-15 11:11 UTC, yurii-litvinov commented on tasks/hw1/list_find/list_find/list_find/Program.fs
> +       | head :: tail -> findSubfunction tail (index + 1)
Тут то же с head

2021-02-15 11:59 UTC, merged